zz_pyro_homepage:
    path:     /
    defaults: { _controller: ZzPyroBundle:Index:index }

zz_pyro_extract:
    resource: "@ZzPyroBundle/Resources/config/routing/extract.yml"
    prefix:   /extract

zz_pyro_video:
    resource: "@ZzPyroBundle/Resources/config/routing/video.yml"
    prefix:   /video
