zz_pyro_homepage:
    path:     /
    defaults: { _controller: ZzPyroBundle:Index:index }

zz_pyro_bestof:
    resource: "@ZzPyroBundle/Resources/config/routing/bestof.yml"
    prefix:   /bestof

zz_pyro_form:
    resource: "@ZzPyroBundle/Resources/config/routing/form.yml"
    prefix:   /form
