services:
    zz_pyro.profile_manager:
        class: Zz\PyroBundle\Entity\ProfileManager
        arguments: [@security.context, @doctrine.orm.entity_manager]

    zz_pyro.youtube_requestor:
        class: Zz\PyroBundle\Entity\YoutubeRequestor
        arguments: [%yt_data_api.dev_key%]

    zz_pyro.form.video:
        class: Zz\PyroBundle\Form\VideoType
        arguments: [@zz_pyro.repo.video, @zz_pyro.youtube_requestor]
        tags:
            - { name: form.type, alias: video }

    zz_pyro.form.video_add:
        class: Zz\PyroBundle\Form\VideoAddType
        tags:
            - { name: form.type, alias: video_add }

    zz_pyro.form.channel:
        class: Zz\PyroBundle\Form\ChannelType
        arguments: [@zz_pyro.repo.channel, @zz_pyro.youtube_requestor]
        tags:
            - { name: form.type, alias: channel }

    zz_pyro.form.extract:
        class: Zz\PyroBundle\Form\ExtractType
        tags:
            - { name: form.type, alias: extract }

    zz_pyro.form.bestof:
        class: Zz\PyroBundle\Form\BestOfType
        tags:
            - { name: form.type, alias: bestof }

    zz_pyro.repo.channel:
        class: Zz\PyroBundle\Entity\ChannelRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['ZzPyroBundle:Channel']

    zz_pyro.repo.video:
        class: Zz\PyroBundle\Entity\VideoRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['ZzPyroBundle:Video']
